@startuml
left to right direction
actor Admin
actor Usuario

rectangle SGO {
  usecase "US01 Login" as UC1
  usecase "US02 Cadastrar competição" as UC2
  usecase "US03 Inscrever atleta" as UC3
  usecase "US04 Alocar local" as UC4
  usecase "US05 Registrar resultados" as UC5
  usecase "US06 Relatório de medalhas" as UC6
}

Admin --> UC1
Admin --> UC2
Admin --> UC3
Admin --> UC4
Admin --> UC5
Usuario --> UC1
Usuario --> UC6
@enduml
